---
title: "El efecto del tabaco sobre el peso de los recién nacidos"
author: "EC1027 --- Econometría I"
date: "Curso 2020-2021"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Planteamiento

La base de datos `bwght` contiene información sobre diversas características de  recién nacidos y sus familias durante el año 1988 en Estados Unidos. En este laboratorio usaremos:

- $\textit{bwght}$: El peso de los recién nacidos, en [onzas](https://www.metric-conversions.org/es/peso/onzas-a-gramos.htm).
- $\textit{male}$: 1 si el recién nacido es varón, 0 si es mujer.
- $\textit{faminc}$: La renta familiar, en miles de dólares.
- $\textit{parity}$: 1 si es el primer hijo de su madre, 2 si es el segundo, etc.
- $\textit{cigs}$: número de cigarrillos que la madre fumaba diariamente durante el embarazo.

Con objeto de estudiar el efecto que tiene el consumo de tabaco durante el embarazo se han propuesto dos modelos alternativos:

- **Modelo 1**:
  $$
  \textit{bwght} = 
  \beta_0 + 
  \beta_1 \textit{faminc} + 
  \beta_2 \textit{male} + 
  \beta_3 \textit{parity} + 
  \beta_4 \textit{cigs} + 
  u
  $$
- **Modelo 2**:
  $$
  \textit{bwght} = 
  \alpha_0 + 
  \alpha_1 \textit{faminc} + 
  \alpha_2 \textit{male} + 
  \alpha_3 \textit{first} + 
  \alpha_4 \textit{cigs_le10} + 
  \alpha_5 \textit{cigs_gt10} + 
  v
  $$
  Para estimar este modelo se han creado las siguientes variables ficticias:

  + $\textit{first}$: toma el valor 1 si la madre no había tenido hijos anteriormente y 0 en caso contrario.
  + $\textit{cigs_le10}$: toma valor 1 si la madre fumó entre 1 y 10 cigarrillos diarios durante el embarazo.
  + $\textit{cigs_le10}$: toma valor 1 si la madre fumó más de 10 cigarrillos diarios durante el embarazo. 

Responda a las siguientes preguntas:

1. ¿Cuál es la interpretación de los parámetros del **Modelo 1**? ¿Y la de los parámetros del **Modelo 2**? ¿Cuál es el signo esperado de esos parámetros?

2. Determine en cuantos casos las madres fumaron durante el embarazo. ¿Cuál es la media de la variable $\textit{cigs}$ si sólo consideramos observaciones en las que las madres fumaron durante el embarazo? 

3. Construya las variables ficticias $\textit{first}$, $\textit{cigs_le10}$ y $\textit{cigs_gt10}$.

4. Estime los dos modelos por MCO. Contraste la presencia de heteroscedasticidad y obtenga, si es necesario, los errores típicos de las estimaciones robustas a heteroscedasticidad.

5. Contraste la correcta especificación de la forma funcional de los dos modelos con el contraste RESET.

6. Compare los dos modelos utilizando contrastes de modelos no anidados. Emplee los contrastes propuestos por Mizon-Richards y los contrastes de Davidson-MacKinnon.

