---
title: "Lab09"
author: "José C. Pernías"
date: "3/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparación

## Bibliotecas de R

```{r}
library(ec1027)
library(zoo)
data(traffic2)
```


```{r}
idx_str <- paste0(traffic2$year, "-", formatC(traffic2$month, width = 2, flag = "0"))
idx <- as.yearmon(idx_str)

traffic2 <- within(traffic2, {
  t <- year - 1981 + (month - 1) / 12
  ltotacc <- log(totacc)
})

seas <- lapply(1:12, function(x) (traffic2$month == x) + 0)
names(seas) <- month.abb
traffic2 <- data.frame(traffic2, as.data.frame(seas))

tr2 <- zoo(traffic2, idx)
```

```{r}
library(ggplot2)
autoplot(tr2$ltotacc)  + geom_point()
```



```{r}
library(dynlm)
rhs <- paste0(c("t", month.abb[-1]), collapse = " + ")
frml_det <- as.formula(paste0(". ~ . + ", rhs))
model1 <- dynlm(update(ltotacc ~ 1, frml_det), data = tr2)
coef_table(model1)
```

```{r}
model2 <- update(model1, . ~ .  + wkends + unem + spdlaw + beltlaw)
coef_table(model2)
```

```{r}
uhat1 <- resid(model1)
model3 <- update(model2, uhat1 ~ .)
summary(model3)
```

```{r}
library(texreg)
screenreg(list(model1, model2, model3), digits = 4)
```


```{r}
prcfat <- 100 * tr2$fatacc / tr2$totacc
mean(prcfat)
```

```{r}
autoplot(prcfat) + geom_point()
```

```{r}
model4 <- update(model2, prcfat ~ .)
summary(model4)
```
 
```{r}
screenreg(list("Modelo 4" = model4), digits = 4)
```
 
```{r}
uhat4 <- resid(model4)
autoplot(uhat4) + geom_point()
```

